### ISSUE TITLE
How to use the datasets/coco_id2tao_id.json

### ISSUE THREAD

**Issue by lalalafloat** [YangLiu14/Open-World-Tracking#4]
Hello, since i have checked coco_id2tao_id.json，i found that there are only 78 keys rather than 80 in the json file. And i try to use coco annotations to convert coco id to tao id, but i failed for some id are not in coco annotations. Could you tell me how to use the coco_id2tao_id.json please ! Thank you !

**Comment by YangLiu14** [comment]
1. only 78 keys in COCO
Yep, the json file doesn't have all 80 COCO ids because there are two ids in COCO that doesn't have correspondence in the TAO dataset.

2. How to use
The json file is simply one-to-one ID-matching between COCO and TAO, so, just use the mapping as it is?

**Comment by lalalafloat** [comment]
> 1. only 78 keys in COCO
>    Yep, the json file doesn't have all 80 COCO ids because there are two ids in COCO that doesn't have correspondence in the TAO dataset.
> 2. How to use
>    The json file is simply one-to-one ID-matching between COCO and TAO, so, just use the mapping as it is?

**Comment by lalalafloat** [comment]
Thank you for your reply. 
The minimum category id in coco's annotations  is "1", but the minimum key in coco_id2tao_id.json is "0". Then I assumed the key in coco_id2tao_id.json was index of the annotations['categories'], but found that the category name in results of the mapping didn't quite correspond either. That's the trouble i met when i mapping the coco_id2tao_id. Hope to get further answers from you, thank you！

**Comment by YangLiu14** [comment]
I was using Detectron2 as the Object Detector, and it outputs class ids from 0 to 79 (if I remember corrrectly, might need to double check that). 
While the full COCO categories have 91 ids, Detectron2 maps them to only 80 categories (something like [this](https://gist.github.com/AruniRC/7b3dadd004da04c80198557db5da4bda)

So if you add one to all the keys in `coco_id2tao_id.json`, and use only that 80 categories, they should be aligned,. 

Thank you for pointing this out, I should write some clarifications about this, or make a new mapping file.
