### ISSUE TITLE
What is the training flow?

### ISSUE THREAD

**Issue by lalalafloat** [YangLiu14/Open-World-Tracking#6]
Hello, we are happy to follow this good job. We met some problems with the training flow. Is the model pre-trained on coco dataset first and then finetuned on the tao_ow_train dataset?

**Comment by YangLiu14** [comment]
Hi, the model (the detector to be precise) is ONLY trained on COCO, and there is no fine-tuning nor any kind of training on the TAO-OW dataset. 
The model we were using is here: https://github.com/YangLiu14/detectron2-OWT

**Comment by lalalafloat** [comment]
> Hi, the model (the detector to be precise) is ONLY trained on COCO, and there is no fine-tuning nor any kind of training on the TAO-OW dataset. The model we were using is here: https://github.com/YangLiu14/detectron2-OWT

Thanks for your quick reply! Since the model does not need to train on TAO-OW dataset, what is the train_split mentioned in paper used for ?

**Comment by YangLiu14** [comment]
Because the object categories in `train_split` is aligned with COCO-classes. So actually we only trained on COCO (namely using the pretrained models from Detectron2).  You can also train/finetune on TAO-OW train-set.  It's just that we did not do this fine-tuning step.
